### ISSUE TITLE
Making first contact with the stimulator always requires a second attempt to succeed

### ISSUE THREAD

**Issue by kuff** [med-material/vrtactility#10]
When you start the app in the `CalibrationScene`, type in the correct port number and click connect, the connection attempt always fails the first attempt after the stimulator has been started. This means the app must be restarted to make another attempt at a connection, which then succeeds. After this, the app can be restarted and a new connection can be made every time until the stimulator is turned off and on again, after which two attempts are again needed to establish a connect the first time.

This may be because the stimulator (or Ardity) for some reason only accepts a reconnection attempt, instead of a new connection attempt. This has been occurring ever since the port to Ardity. The no-questions-asked solution to this would be to just programmatically make two connection attempts every time the app starts, deliberately ignoring the first attempt. There should exist a more elegant fix to this, and it might be a simple oversight on my part, but I need to investigate further to confirm.

Once I'm able, I'll expand on this issue with the console logs from Unity....

**Comment by MartinGarenfeld** [comment]
A permanent fix could likely be closing all identified valid serial ports as the first thing when the app starts, before establishing connection with the stimulator. I think we also talked about this at a meeting sometime, but it seemed like there was not a straightforward solution on how to implement this. But I assume it should be possible.

**Comment by kuff** [comment]
Entire console output for first connection attempt:

![image](https://user-images.githubusercontent.com/16867891/212316144-050bfd23-96bc-4f52-a511-bbc048c603f4.png)

Entire second console output from second (successful) connection attempt:

![image](https://user-images.githubusercontent.com/16867891/212316249-31e09647-60da-4a60-a580-3eba920413e2.png)

On the surface, this doesn't tell us a lot other than there being a series of erroneous connection attempts in the first attempt, which are not present in the second one.

> A permanent fix could likely be closing all identified valid serial ports as the first thing when the app starts, before establishing connection with the stimulator. I think we also talked about this at a meeting sometime, but it seemed like there was not a straightforward solution on how to implement this. But I assume it should be possible.

Will definitely try this.

**Comment by kuff** [comment]
Fixed as of https://github.com/med-material/vrtactility/commit/4ae90dd843720c9dadbb4c95c2082b1da9966c00.
