### ISSUE TITLE
Ball rotational axis is not managed like the positional axis

### ISSUE THREAD

**Issue by kuff** [med-material/vrtactility#16]
The ball rotational axis is not managed at all, and is incidentally not observable because it is a solid color with no texture on it. However, when inspected in the Unity Editor, after the user has grabbed the ball and released it again, the rotation axis is not handled and the ball carries over all rotational velocity from the interaction:

![Unity_Srwt0wgxZH](https://user-images.githubusercontent.com/16867891/212771475-2256d46f-5e21-4b04-9535-801293927874.gif)

With the current rendition of the ball this is not an issue as it is not observable by the user and does not affect current logic in any way. However, if we were to decide to texture the ball in any way in the future, or potentially use a non-uniform object in its stead, this will need to be dealt with and is still considered undesired behavior for that reason.

**Comment by mathiassand** [comment]
Depending on what behavior we want from the sphere, can't we just freeze the rigidbody rotation? e.g., 

Rigidbody ball_Rigidbody;
void start() {
     ball_Rigidbody = GetComponent<Rigidbody>(); 
     ball_Rigidbody.freezeRotation = true;
}

**Comment by kuff** [comment]
> Depending on what behavior we want from the sphere, we can try freezing the rigidbody rotation, i.e.,
> 
> Rigidbody ball_Rigidbody; void start() { ball_Rigidbody = GetComponent(); ball_Rigidbody.freezeRotation = true; }

Would this not also freeze the rotation for when it's being manipulated by the user? In that case I don't think it's a valid solution. We could freeze/unfreeze it depending on if it's being grabbed to mitigate this, but then the ball would just stop rotating instantly when its released, which I don't think is very believable behavior and would take the user out of the experience somewhat.

My current idea is to simply apply the same counter-acting forces to the rotational axis, as I'm already doing for the positional axis (when the ball is released and it glides back to its origin point).

**Comment by mathiassand** [comment]
Not sure exactly how it would impact while grabbing, but that might be the case. We definitely want believable behavior. Sounds good :)

**Comment by kuff** [comment]
Fixed as of https://github.com/med-material/vrtactility/commit/199eca73b35c0ed2654045ad83f2fad492648a3d.
