### ISSUE TITLE
intensity is too strong

### ISSUE THREAD

**Issue by kuff** [med-material/vrtactility#25]
The stimulator appears to be overstepping the calibration threshold when administrating stimuli.

The calculations should be reworked to ensure that they only overstep by a fixed amount, for example 10%. Furthermore, considerations should be made about the need to factoring down the amplitude in accordance with how many pads are being stimulated per finger.

**Comment by stef5949** [comment]
Updated to now use the correct amplitude values and added a modifier for adjusting.
