### ISSUE TITLE
_glovePort.Write seems to not work in TrackingScene

### ISSUE THREAD

**Issue by kuff** [med-material/vrtactility#4]
The SerialPort.Write op in the TactilityManager, although it doesn't error, seems to not have any effect, as even a maximum stimulator value of 7.5 is not perceivable when interfacing with the stimulator in this scene.

![image](https://user-images.githubusercontent.com/16867891/210735280-fcadab51-9971-4901-beae-71d215104505.png)

The issue may possibly be in the logic for generating the Command string which is passed to the SerialPort.Write method. This logic is taken directly from the brush stroke example discussed during our most recent meeting, but has been slightly refactored.

The issue may also be because some finalization steps are taken when transitioning from the calibration scene to the tracking scene, although this would've presumably been the same steps taken in the brush stroke experiment, and thus should not result in the SerialPort reference becoming inoperable.

**Comment by kuff** [comment]
The entire GenerateCommandString method for context:

````csharp
private string GenerateCommandString(IReadOnlyList<float> pressureValues)
{
    var completeString = "";
    
    const string invariablePart1 = "velec 11 *special_anodes 1 *name test *elec 1 *pads ";
    const string invariablePart2 = " *amp ";
    const string invariablePart3 = " *width ";
    var finalPart = pressureValues.All(value => value == 0)  // If sum is zero then we disable all electrodes
        ? " *selected 0 *sync 0\r\n" 
        : " *selected 1 *sync 0\r\n";

    var variablePart1 = "";
    var variablePart2 = "";
    var variablePart3 = "";

    for (var i = 0; i < 32; i++)
    {
        // Use remap value to determine which finger pressure value we use
        var pressureValue = i switch
        {
            < 8  => pressureValues[0],
            < 21 => pressureValues[1],
            < 26 => pressureValues[2],
            < 31 => pressureValues[3],
            _    => pressureValues[4]  // == 31
        };
        // if (i < 8) Debug.Log(_pads[i].GetAmplitude() * pressureValue);

        variablePart1 += _pads[i].GetRemap() + "=C,";
        variablePart2 += _pads[i].GetRemap() + "=" + _pads[i].GetAmplitude() * pressureValue + ",";
        variablePart3 += _pads[i].GetRemap() + "=" + _pads[i].GetPulseWidth() + ",";
    }

    // Build final string and return
    completeString = invariablePart1 
                     + variablePart1 
                     + invariablePart2 
                     + variablePart2 
                     + invariablePart3 
                     + variablePart3 
                     + finalPart;
    return completeString;
}
````

**Comment by MartinGarenfeld** [comment]
You need to make sure that you are passing on the same instance of the serial connection as the the one established for the calibration scene. You can try and send the 'stim on' and 'stim off' commands in the Tracking Scene and see if the yellow LED turns on at 'stim on' and off at 'stim off' - then the serial connection is fine. If the blue LED starts blinking you lost the connection and it is not the same instance of the serial connection.

The 'stim on' commands needs to have been sent in order to trigger stimulation. 

You should also check that the decimal numbers in the amp values are separated by . and not ,

You can also try and turn up the pulse width (stimulation intensity is a product of pulse width and amplitude). Maximum pulse width is 500 us and maximum amplitude is 9 mA. 

In general, it is a good idea at first to print the command string to check if the command syntax is correctly written. Test with simple commands/stimulation first to make sure the syntax is correct and then move on.

**Comment by kuff** [comment]
Thanks for the quick response. 

The blue- and yellow LEDs are on continuously in the CallibrationScene. I was able to get it to stimulate by copy-pasting the amplitude stimulate logic from the UIManager (the one that only stimulates the a single pad). This means the issue is almost certainly because of how the command string is being assembled in my code. I have previously examined the command string by printing it to the console, but I have not spotted any issues. I will probably try getting the logic from the brush stroke example to print to the console so that I have something to compare with what my code generates. I feel like we're getting there though, thanks again.

**Comment by kuff** [comment]
Upon further investigation, I was able to get it to stimulate the first pad index (remapped to pad 30, which is a pad on the thumb) with an amplitude of 4.0 when that was the only element being included in the GenerateCommandString method:

`
velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C, *amp 30=4, *width 30=100, *selected 1 *sync 0
`

Whereas the string normally produced with the same method doesn't work, although the input values are identical (note that only the thumb amplitude values were changed to 4 during the calibration and the rest of the fingers have their default value of 0.5):

`
velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C,27=C,29=C,28=C,25=C,31=C,32=C,26=C,17=C,18=C,20=C,1=C,2=C,22=C,19=C,3=C,23=C,21=C,24=C,4=C,5=C,8=C,9=C,6=C,7=C,10=C,13=C,14=C,11=C,12=C,15=C,16=C, *amp 30=4,27=4,29=4,28=4,25=4,31=4,32=4,26=4,17=0.5,18=0.5,20=0.5,1=0.5,2=0.5,22=0.5,19=0.5,3=0.5,23=0.5,21=0.5,24=0.5,4=0.5,5=0.5,8=0.5,9=0.5,6=0.5,7=0.5,10=0.5,13=0.5,14=0.5,11=0.5,12=0.5,15=0.5,16=0.5, *width 30=100,27=100,29=100,28=100,25=100,31=100,32=100,26=100,17=100,18=100,20=100,1=100,2=100,22=100,19=100,3=100,23=100,21=100,24=100,4=100,5=100,8=100,9=100,6=100,7=100,10=100,13=100,14=100,11=100,12=100,15=100,16=100, *selected 1 *sync 0
`

Is there somehow a limit to how long the command string can be? Or is the string incorrectly formatted in some way? Or do I need to manually exclude one pad from each finger to allow for the flow of electricity?

**Comment by kuff** [comment]
I was also able to get it to work when stimulating pads 0 and 1 simultaneously (remaps into pads 30 and 27 respectively):

`
velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C,27=C, *amp 30=4,27=4, *width 30=100,27=100, *selected 1 *sync 0
`

Is it simply the case that I must leave one pad unused for each finger?

**Comment by MartinGarenfeld** [comment]
> Upon further investigation, I was able to get it to stimulate the first pad index (remapped to pad 30, which is a pad on the thumb) with an amplitude of 4.0 when that was the only element being included in the GenerateCommandString method:
> 
> `velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C, *amp 30=4, *width 30=100, *selected 1 *sync 0`
> 
> Whereas the string normally produced with the same method doesn't work, although the input values are identical (note that only the thumb amplitude values were changed to 4 during the calibration and the rest of the fingers have their default value of 0.5):
> 
> `velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C,27=C,29=C,28=C,25=C,31=C,32=C,26=C,17=C,18=C,20=C,1=C,2=C,22=C,19=C,3=C,23=C,21=C,24=C,4=C,5=C,8=C,9=C,6=C,7=C,10=C,13=C,14=C,11=C,12=C,15=C,16=C, *amp 30=4,27=4,29=4,28=4,25=4,31=4,32=4,26=4,17=0.5,18=0.5,20=0.5,1=0.5,2=0.5,22=0.5,19=0.5,3=0.5,23=0.5,21=0.5,24=0.5,4=0.5,5=0.5,8=0.5,9=0.5,6=0.5,7=0.5,10=0.5,13=0.5,14=0.5,11=0.5,12=0.5,15=0.5,16=0.5, *width 30=100,27=100,29=100,28=100,25=100,31=100,32=100,26=100,17=100,18=100,20=100,1=100,2=100,22=100,19=100,3=100,23=100,21=100,24=100,4=100,5=100,8=100,9=100,6=100,7=100,10=100,13=100,14=100,11=100,12=100,15=100,16=100, *selected 1 *sync 0`
> 
> Is there somehow a limit to how long the command string can be? Or is the string incorrectly formatted in some way? Or do I need to manually exclude one pad from each finger to allow for the flow of electricity?

When you send such a long command string the stimulator uses much more processing time and there is a great probability of overload. So it is definitely best to send only the pads you want to activate every time you send a command. And the newest command overwrites the previous, such that if you for instance activate only pads 1 and 2 with one command and with the next command you activate only pads 3 and 4, pads 1 and 2 are automatically deactivated.

**Comment by MartinGarenfeld** [comment]
> I was also able to get it to work when stimulating pads 0 and 1 simultaneously (remaps into pads 30 and 27 respectively):
> 
> `velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C,27=C, *amp 30=4,27=4, *width 30=100,27=100, *selected 1 *sync 0`
> 
> Is it simply the case that I must leave one pad unused for each finger?

Yes, you need to not activate all pads in the same finger. I found that in the thumb you need at least 2 pads unused, 4 in the index and 1 in the middle and 1 in the ring finger for a stable stimulation.

**Comment by kuff** [comment]
hey @MartinGarenfeld 

I've ported the ConnectDevice interface to use the [Ardity](https://github.com/dwilches/Ardity) library as discussed in [issue #3](https://github.com/med-material/vrtactility/issues/3), and it has the added side-effect of allowing me to print out the responses to all commands i send to the stimulator.

Normally, when I send non-zero values, it gives an ok response, but when I send values of zero amplitude to the stimulator, I get an error message back. An example of a command I've sent in testing, where all pads on the thumb except two are invoked:

`
velec 11 *special_anodes 1 *name test *elec 1 *pads 30=C,27=C,29=C,28=C,25=C,31=C, *amp 30=0,27=0,29=0,28=0,25=0,31=0, *width 30=100,27=100,29=100,28=100,25=100,31=100, *selected 1 *sync 0
`

And the response:

`
Re:[] Error. The PADS defined as CATHODES don't correspond to the pads used for AMP
`

I have not explicitly defined any anodes, as I remember it being brought up at a previous meeting that the stimulator automatically assigns the non-cathode pads to be anodes. Is this correctly understood, or should I somehow explicitly define the anodes and in that case how?

A way of avoiding the error could be to just send a very small value to the pads, but in my logic I kind of need a way to make sure pads are turned off, and I cannot necessarily rely on there being issued another command later, which does not reference these pads, thereby turning them off as you described earlier. Do you have experience on this error and how to handle it, or what are your thoughts?

Deciding how to handling this might prove vital, as I will have to minimize the number of pads I invoke to minimize the chance of the stimulator being overloaded. I might be able to mitigate this by separating each finger into its own command, which would just cycle each finger on/off in a sequence, but if done fast enought it might feel concurrent.

On that note, do you have any intuition about how often commands can be sent to the stimulator and still have them be recognized? I have tried sending commands as often as every 20 milliseconds, as this was a threshold that was brought up in a previous meeting, but although the stimulator responds with ok, I'm still not entirely sure it registers.

**Comment by MartinGarenfeld** [comment]
The stimulation frequency, amplitude and pulse width can be modulated in the range of 1-200 Hz, 0.5-9 mA and 30-500 µs with 1 Hz, 0.1 mA and 10 µs increments, respectively. These values are also default minimum and maximum values in calibration scene. So you cannot send 0 amp to a pad (minimum is 0.5 mA), which is likely the reason for the error. Yes, you do not need to define anodes because of the automatic assignment when using the *special_anodes option. 

You can deactivate the stimulation by sending the 'stim off' command. This untriggers the possibility of stimulating and turns off the orange LED. However, this is taxing for the hardware as you need to also send the 'stim on' command every time you need to trigger stimulation and should therefore not be used for this. Basically only use it when you are done using the stimulator or as a safety precaution.
As we discussed in the previous meeting, you can instead use the *selected 0 option, which means that you deactivate the indicated velec without untriggering the stimulation. As you can see in the command message you send to the stimulator is says 'velec 11 ........ *selected 1 ...'. To deactivate stimulation you only need to indicate the velec and selected 0, so the command string would be: 'velec 11 *selected 0'. In an example, this command string should be send when the hand looses contact with the object. 

Regarding the minimum time between commands messages, the more commands are in a string, e.g. more pads, the more processing time is needed. But 20 ms is be fine for all commands you are sending.

**Comment by kuff** [comment]
This is now considered fixed as of https://github.com/med-material/vrtactility/pull/6:

> The TactilityManager now stimulates by regulating the amplitude of the stimulator and does so in relation to how much pressure the user is exerting on the ball.

Tested using the thumb only, but the command being submitted includes all fingers and is not rejected by the stimulator. Anode pads are selected manually, currently they are:

- Thumb: 1 and 2.
- Index: 9, 10, 11, and 12.
- Middle: 23.
- Ring: 28.
- Pinky: Only has one pad, and thus does not require anode assignation.

See [this post](https://github.com/med-material/vrtactility/issues/2#issuecomment-1374011303) for reference.

**Comment by MartinGarenfeld** [comment]
Very good, great progress you are making! 
Again you do not not need to assign any pads as anodes at any time. The "*special_anodes" option handles this for you. And I would very much recommend using more proximally and centered placed pads as "anodes" as the distal part of the finger is what commonly is first in contact with an object. Below is an example of the spatial force modulation with 4 levels and the pads active in each level (see image you referenced in the previous post) and the corresponding commands string (the example uses all fingers in each level):

Level 1 pads active: 1     9    22    27    32
Level 2 pads active: 1     2     9    10    22    23    27    28    32
Level 3 pads active: 1     2     3     5     9    10    11    13    22    23    24    27    28    29    32
Level 4 pads active: 1     2     3     5     7     9    10    11    13    15    22    23    24    26    27   28    29    31    32

Level 1 command string:
velec 11 *special_anodes 1 *name testve11 *elec 1 *pads 30=C,17=C,8=C,13=C,16=C, *amp 30=0.5,17=0.5,8=0.5,13=0.5,16=0.5, *width 30=200,17=200,8=200,13=200,16=200, *selected 1 *sync 0

Level 2 command string:
velec 11 *special_anodes 1 *name testve11 *elec 1 *pads 30=C,27=C,17=C,18=C,8=C,9=C,13=C,14=C,16=C, *amp 30=0.5,27=0.5,17=0.5,18=0.5,8=0.5,9=0.5,13=0.5,14=0.5,16=0.5, *width 30=200,27=200,17=200,18=200,8=200,9=200,13=200,14=200,16=200, *selected 1 *sync 0

Level 3 command string
velec 11 *special_anodes 1 *name testve11 *elec 1 *pads 30=C,27=C,29=C,25=C,17=C,18=C,20=C,2=C,8=C, 9=C,6=C,13=C,14=C,11=C,16=C, *amp 30=0.5,27=0.5,29=0.5,25=0.5,17=0.5,18=0.5,20=0.5,2=0.5,8=0.5, 9=0.5,6=0.5,13=0.5,14=0.5,11=0.5,16=0.5, *width 30=200,27=200,29=200,25=200,17=200,18=200,20=200,2=200,8=200, 9=200,6=200,13=200,14=200,11=200,16=200, *selected 1 *sync 0

Level 4 command string:
velec 11 *special_anodes 1 *name testve11 *elec 1 *pads 30=C,27=C,29=C,25=C,32=C,17=C,18=C,20=C,2=C, 19=C,8=C,9=C,6=C,10=C,13=C,14=C,11=C,15=C, 16=C, *amp 30=0.5,27=0.5,29=0.5,25=0.5,32=0.5,17=0.5,18=0.5,20=0.5,2=0.5, 19=0.5,8=0.5,9=0.5,6=0.5,10=0.5,13=0.5,14=0.5,11=0.5,15=0.5, 16=0.5,  *width 30=200,27=200,29=200,25=200,32=200,17=200,18=200,20=200,2=200, 19=200,8=200,9=200,6=200,10=200,13=200,14=200,11=200,15=200, 16=200,  *selected 1 *sync 0

**Comment by kuff** [comment]
Apologies, I realize now my wording was off. I do not actually send commands designating any pads explicitly as anodes, rather I just skip including those pads in the stim command, such that the system automatically assigns those to be anodes as previously discussed and as you mention again here. Sorry for the confusion.

I picked those pads because I find when grabbing the sphere that I would expect the lower parts of my fingers to experience the most contact with the object. My plan is definitely to make this easily adjustable however, and I do not consider a lot of these things to be final.

Thanks for the spatial mappings - I'll have a look at implementing them but I may be a bit busy this week.

**Comment by MartinGarenfeld** [comment]
No worries. And I see your point about which part of the fingers are touching the object first. So it might be a good idea to keep the cathode/anode configuration as you initially thought to. But what feels more natural needs to be determined in practical testing anyways.
